<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0f3edp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0f3edp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0f3edp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0f3edp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM0f3edp\App_KernelDevDebugContainer([
    'container.build_hash' => 'M0f3edp',
    'container.build_id' => '19b82e36',
    'container.build_time' => 1578271389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0f3edp');
