<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFs4T3Af\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFs4T3Af/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFs4T3Af.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFs4T3Af\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFs4T3Af\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fs4T3Af',
    'container.build_id' => 'cd057a1e',
    'container.build_time' => 1578273309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFs4T3Af');
