<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSGNrjEB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSGNrjEB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSGNrjEB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSGNrjEB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSGNrjEB\App_KernelDevDebugContainer([
    'container.build_hash' => 'SGNrjEB',
    'container.build_id' => 'e9891134',
    'container.build_time' => 1578269645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSGNrjEB');
